const countryList = {
  "USD": "US",
  "INR": "IN",
  "EUR": "EU",
  "GBP": "GB",
  "JPY": "JP",
  "AUD": "AU",
  "CAD": "CA",
  "CHF": "CH",
  "CNY": "CN",
  "SGD": "SG",
  "NZD": "NZ",
  "ZAR": "ZA",
  "AED": "AE",
  "SAR": "SA",
  "THB": "TH",
  "MYR": "MY",
  "KRW": "KR",
  "RUB": "RU",
  "BRL": "BR",
  "MXN": "MX",
  "IDR": "ID",
  "TRY": "TR"
};
